version: "1.0"
logging:
    log_file_name: folder_monitor.log
    log_folder: logs
    # log_folder: C:/Apps/FolderMonitor/logs
    log_max_file_size: 1000000
    log_max_backup_count: 5
    # log_level: debug | info | warning | error | critical
    log_level: debug

monitors: 
    - name: "cloud to idrive"
      enabled: true
      monitor_path: "D:/Cloud"
      destination_path: "e2:john-zoetebier-net/Cloud"
      rclone_flags: "--transfers, 8, --s3-no-check-bucket"
      backup:
        enabled: false
        interval: "0s" # Backup runs once only immediately after start. This is the default. Any previous folder changes will be submitted to the destination.
        mode: "copy"
   
