  # version: application version
  # logging: logging properties
  # monitors: list of monitors
  #   name: name of the monitor
  #   enabled: true | false
  #   monitor_path: "folder to monitor"
  #   destination_path: "cloud storage, local folder or shared folder"
  #   rclone_flags: rcone flags specific for this monitor
  #     if flags are stored in the rclone configuration there is no reason to repeat then here.
  #   testing: properties used for testing properties, for development or issue isolation.
  # backup: set of properties to run one or more backups
  #   At least one backup is required to upload loacal files to the destination.
  #   enabled: true | false
  #   interval: s | 
  #   mode: copy | sync
  #       copy files to destination
  #       sync will delete files in destination_path that are not in source folder. 


version: "1.0"

logging:
  log_file_name: folder_monitor.log
  log_folder: logs # relative or full path like C:/Apps/FolderMonitor/logs.
  log_max_file_size: 1000000
  log_max_backup_count: 5
  log_level: debug # debug | info | warning | error | critical

monitors:
  - name: "Idrive e2"
    enabled: true
    monitor_path: "D:/Development/FolderMonitor/data/Source/Idrive"
    destination_path: "e2:test-foldermonitor/Idrive"
    rclone_flags: "--transfers 8 --s3-no-check-bucket"
    exclude_patterns: 
      - "excluded folder"
    testing:
      check_delay: 3
    backup:
      enabled: true
      interval: "1d"
      mode: "copy"
 
  - name: "Backblaze b2"
    enabled: true
    monitor_path: "D:/Development/FolderMonitor/data/Source/Backblaze"
    destination_path: "b2:test-foldermonitor/Backblaze"
    rclone_flags: "--transfers 8"
    exclude_patterns: 
      - "excluded folder"
    # testing:
    #   check_delay: 3
    backup:
      enabled: true
      interval: ""
      mode: "copy"

  - name: "Internxt drive"
    enabled: true
    monitor_path: "D:/Development/FolderMonitor/data/Source/internxt-drive"
    destination_path: "internxt:test-foldermonitor/internxt-drive"
    rclone_flags: >
      --webdav-method PUT
      --tpslimit 4
      --ignore-times
      --no-check-certificate
    exclude_patterns: 
      - "excluded folder"
    testing:
      check_delay: 3
    backup:
      enabled: true
      interval: ""
      mode: "copy"
 
