version: "1.0"

logging:
  log_file_name: monitor_test.log
  log_folder: logs
  log_max_file_size: 1000000
  log_max_backup_count: 5
  # log_level: debug | info | warning | error | critical
  log_level: debug

monitors:
  # - name: "local storage"
  #   enabled: true
  #   monitor_path: "data/Source/local-storage"
  #   destination_path: "data/Destination/local-storage"
  #   rclone_flags: "--transfers 4"
  #   testing:
  #     check_delay: 1
  #   backup:
  #     enabled: enabled
  #     interval: ""
  #     mode: "copy"

  # - name: "nas1 ftp storage"
  #   enabled: true
  #   monitor_path: "data/Source/nas1-ftp-storage"
  #   destination_path: "nas1-ftp:foldermonitor"
  #   rclone_flags: "--transfers 4"
  #   testing:
  #     check_delay: 1
  #   backup:
  #     enabled: false
  #     interval: ""
  #     mode: "copy"

  - name: "idrive-cloud-storage-not-versioned"
    enabled: true
    monitor_path: "data/Source/idrive-cloud-storage"
    destination_path: "e2:test-foldermonitor/idrive-cloud-storage"
    rclone_flags: "--s3-no-check-bucket"
    exclude_patterns: 
      - "excluded-folder"
      - "*.tmp"
    testing:
      check_delay: 3
    backup:
      enabled: false
      interval: ""
      mode: "copy"


  # - name: "idrive-cloud-storage-versioned"
  #   enabled: true
  #   monitor_path: "data/Source/idrive-cloud-storage"
  #   destination_path: "e2:test-foldermonitor-versioned/idrive-cloud-storage"
  #   rclone_flags: "--transfers 4 --s3-no-check-bucket"
  #   exclude_patterns: 
  #     - "excluded folder"
  #   testing:
  #     check_delay: 3
  #   backup:
  #     enabled: false
  #     interval: ""
  #     mode: "copy"

  # - name: "backblaze-cloud-storage"
  #   enabled: true
  #   monitor_path: "data/Source/backblaze-cloud-storage"
  #   destination_path: "b2:test-foldermonitor/backblaze-cloud-storage"
  #   rclone_flags: "--transfers 4 --s3-no-check-bucket"
  #   testing:
  #     check_delay: 5
  #   backup:
  #     enabled: false
  #     interval: ""
  #     mode: "copy"

  # - name: "cloudflare-cloud-storage"
  #   enabled: true
  #   monitor_path: "data/Source/cloudflare-cloud-storage"
  #   destination_path: "r2:test-foldermonitor/cloudflare-cloud-storage"
  #   rclone_flags: "--transfers 4 --s3-no-check-bucket"
  #   testing:
  #     check_delay: 3
  #   backup:
  #     enabled: false
  #     interval: ""
  #     mode: "copy"

  # - name: "google drive cloud storage - personal credentials"
  #   enabled: true
  #   monitor_path: "data/Source/google-drive-personal"
  #   destination_path: "drive-personal:test-foldermonitor/google-drive-personal"
  #   rclone_flags: "--transfers 4 --fast-list"
  #   testing:
  #     check_delay: 10
  #   backup:
  #     enabled: false
  #     interval: ""
  #     mode: "copy"

  # - name: "google drive cloud storage - generic credentials"
  #   enabled: true
  #   monitor_path: "data/Source/google-drive-generic"
  #   destination_path: "drive:test-foldermonitor/google-drive-generic"
  #   rclone_flags: "--transfers 4 --fast-list"
  #   testing:
  #     check_delay: 20
    # backup:
  #   # enabled: false
  #   # interval: ""
  #   # mode: "copy"


