version: "2.0.0"
# On Windows use forward slash "/"
# Good: C:/path/to/monitor
# Bad: C:\path\to\monitor
monitors:
  - name: "multi-remote-test"
    monitor_path: "data/Source/multi-remote-test"
    remote_path: "test-foldermonitor/multi-remote-test"
    remote_profiles:
      - "rclone-idrive-test"
      - "backblaze-test"
    exclude_patterns: 
      - "excluded-folder"
      - "*.tmp"
    backup:
      interval: ""

  - name: "idrive-test-not-versioned"
    monitor_path: "data/Source/idrive-cloud-storage"
    remote_path: "test-foldermonitor/idrive-cloud-storage"
    remote_profiles:
      - "rclone-idrive-test"
    exclude_patterns: 
      - "excluded-folder"
      - "*.tmp"
    backup:
      interval: ""

  - name: "idrive-cloud-storage-versioned"
    monitor_path: "data/Source/idrive-cloud-storage"
    remote_path: "test-foldermonitor-versioned/idrive-cloud-storage"
    remote_profiles:
      - "e2"
    exclude_patterns: 
      - "excluded folder"
    backup:
      interval: ""
  

  - name: "backblaze-cloud-storage"
    monitor_path: "data/Source/backblaze-cloud-storage"
    remote_path: "test-foldermonitor/backblaze-cloud-storage"
    remote_profiles:
      - "b2"
    backup:
      interval: ""
  
  - name: "cloudflare-cloud-storage"
    monitor_path: "data/Source/cloudflare-cloud-storage"
    remote_path: "test-foldermonitor/cloudflare-cloud-storage"
    remote_profiles:
      - "r2"
    backup:
      interval: ""
  

  - name: "google drive cloud storage - personal credentials"
    monitor_path: "data/Source/google-drive-personal"
    remote_path: "test-foldermonitor/google-drive-personal"
    remote_profiles:
      - "drive-personal"
    backup:
      interval: ""
  

  - name: "google drive cloud storage - generic credentials"
    monitor_path: "data/Source/google-drive-generic"
    remote_path: "test-foldermonitor/google-drive-generic"
    remote_profiles:
      - "drive"
    backup:
      interval: ""

  - name: "local storage"
    monitor_path: "data/Source/local-storage"
    remote_path: "data/Destination/local-storage"
    backup:
      interval: ""

  - name: "nas1 ftp storage"
    monitor_path: "data/Source/nas1-ftp-storage"
    remote_path: "foldermonitor"
    remote_profiles:
      - "nas1-ftp"
    backup:
      interval: ""
